### PR TITLE
Keep GitHub build artifacts

### PR DESCRIPTION
**Pull request by expede**

### CODE REVIEW

**Comment by expede** [comment]
Hey hey it works

Screen Shot 2021-03-28 at 8 35 46 PM

**Comment by expede** [comment]
@walkah I want to do some renaming here, just just FYI ☝️

**Comment by walkah** [comment]
@expede is this what I think it is? Actions building our binaries for release? 👍 😍 🥳

**Comment by expede** [comment]
> @expede is this what I think it is? Actions building our binaries for release? 👍 😍 🥳

That's correct! It's not _fully_ automated (for e.g. Homebrew), but it lets us skip building `n` versions locally.

I also want to use this to create a Nix derivation for nixpkgs that describes the runtime dynamic libraries and pulls the prebuilt binary rather than building from source.

**Comment by walkah** [comment]
> That's correct! It's not _fully_ automated (for e.g. Homebrew), but it lets us skip building `n` versions locally.

it's an awesome first step!
 
> I also want to use this to create a Nix derivation for nixpkgs that describes the runtime dynamic libraries and pulls the prebuilt binary rather than building from source.

:nixosintensifies:

**Comment by expede** [comment]
Running an experiment on the Nixified actions... one sec...

**Pull request merged**
