### PR TITLE
Let user know when their email is invalid

### LINKED ISSUE #384: Let CLI user know when their email is invalid
NB: Feature requests will only be considered if they solve a pain

# Summary

## Problem

At time of writing, if email verification cannot be sent (e.g. malformed email address), we return a generic `HTTP 500`. It would be good to return a `422` and message about being unable to send the verification email. Also should probably revert the account, too.

### Impact

* Harder to debug
* Confusing for the user when it fails

## Solution

* 500 -> 422
* Descriptive message

### PR DESCRIPTION
**Pull request by erlandsona**
closes #384

### CODE REVIEW

**Review by expede — APPROVED** [review]
This is much simpler than what I had in my head 😆  I love it!

Pending CI:

**Comment by expede** [comment]
Hmm don't worry about Cachix failing. We can figure that out separately 🤔

**Comment by erlandsona** [comment]
Yeh sounds good... and no worries. It was actually a god confidence booster as a first issue to just find my way around the code base and knock something out. Granted, if you want what was in your head feel free to elaborate and I'll do my best to accommodate. 
As in the other PR, I didn't actually know how to test this but given the requirements it seemed straightforward enough :man_shrugging:

**Comment by expede** [comment]
> Granted, if you want what was in your head feel free to elaborate and I'll do my best to accommodate.

This PR is great as-is. Being pragmatic is a virtue 👍

**Pull request merged**
